version: "2"
services:
  app:
    build: ./app
    links:
      - db
    ports:
      - "5000:5000"
    depends_on:
      - db
    volumes:
      - ./sqls:/tmp/
  db:
    image: mysql:5.7
    container_name: mysql_flask
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro